In [ ]:
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
arr = np.full((3,3) , True , dtype = bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = ar[ar % 2 != 0]
print(odd)

[1 3 5 7 9]


In [ ]:
ar = np.arange(10)


In [ ]:
arr = np.arange(10)
result = np.where(ar % 2 != 0 , -1 , arr)
print(arr)
result

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
md = np.arange(10)
re = arr.reshape(2 , -1)
print(re)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
m1 = np.concatenate((a, b), axis=0)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
n1 = np.vstack((a,b))
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
n = np.hstack((a,b))
n

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
n = np.intersect1d(a,b)
n

array([2, 4])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
diff = np.setdiff1d(a,b)
diff

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.where( a == b)
common


(array([1, 3, 5, 7]),)

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
d = (a >= 5) & (a <= 10)
e = a[d]
e


array([ 6,  9, 10])

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
result = pair_max(a,b)
result

array([6., 7., 9., 8., 9., 7., 5.])

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[[0,1,2]] = arr[[-1,-2,-3]]
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
arr[::-1]
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
arr[:,[0,1,2]] = arr[:,[-1,-2,-3]]
arr

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [ ]:
arr[:, ::-1]
arr

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [ ]:
import random as rand

In [ ]:
np.random.uniform(5,10,size=(5,3))

array([[5.5584979 , 8.52233476, 5.83553056],
       [7.77929255, 5.31160917, 5.68899875],
       [9.19107632, 9.64966795, 5.36407328],
       [8.09991049, 6.76605086, 6.54872568],
       [5.98955322, 5.64776293, 6.859766  ]])

In [ ]:
rand_arr = np.random.random((5,3))
rounded2 = np.set_printoptions(precision=3)
rand_arr

array([[0.167, 0.091, 0.776],
       [0.27 , 0.856, 0.286],
       [0.752, 0.03 , 0.638],
       [0.156, 0.645, 0.134],
       [0.907, 0.408, 0.34 ]])

In [ ]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress = True , precision = 6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [ ]:
a = np.arange(15)
np.set_printoptions(threshold= 10 , edgeitems = 3)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [ ]:
np.set_printoptions(threshold=6)
a = np.arange(15)


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [ ]:
b = iris[0]
b

array([4.9, 3. , 1.4, 0.2])

In [ ]:

a = np.genfromtxt(url,delimiter = ',' , dtype = 'float' , skip_header = 1 , usecols = [1,2,3])
a

array([[3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.1, 1.5, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3, 0.3],
       [3.2, 1.3

In [ ]:
mean = np.mean(iris)
median = np.median(iris)
std = np.std(iris)
values, counts = np.unique(iris, return_counts=True)
mode = values[np.argmax(counts)]

In [ ]:
mean

np.float64(2.6769574944071586)

In [ ]:
median

np.float64(2.7)

In [ ]:
mode

np.float64(0.2)

In [ ]:
std

np.float64(1.5650350841907936)

In [ ]:
iris_data = np.genfromtxt(url, delimiter = ',' , dtype = 'float' , usecols = [1] , skip_header = 1)

In [ ]:
a = np.max(iris_data)
b = np.min(iris_data)
((iris_data - b)/(a-b))


array([0.41666667, 0.5       , 0.45833333, 0.66666667, 0.79166667,
       0.58333333, 0.58333333, 0.375     , 0.45833333, 0.70833333,
       0.58333333, 0.41666667, 0.41666667, 0.83333333, 1.        ,
       0.79166667, 0.625     , 0.75      , 0.75      , 0.58333333,
       0.70833333, 0.66666667, 0.54166667, 0.58333333, 0.41666667,
       0.58333333, 0.625     , 0.58333333, 0.5       , 0.45833333,
       0.58333333, 0.875     , 0.91666667, 0.45833333, 0.5       ,
       0.625     , 0.45833333, 0.41666667, 0.58333333, 0.625     ,
       0.125     , 0.5       , 0.625     , 0.75      , 0.41666667,
       0.75      , 0.5       , 0.70833333, 0.54166667, 0.5       ,
       0.5       , 0.45833333, 0.125     , 0.33333333, 0.33333333,
       0.54166667, 0.16666667, 0.375     , 0.29166667, 0.        ,
       0.41666667, 0.08333333, 0.375     , 0.375     , 0.45833333,
       0.41666667, 0.29166667, 0.08333333, 0.20833333, 0.5       ,
       0.33333333, 0.20833333, 0.33333333, 0.375     , 0.41666

In [ ]:
softmax = np.exp(iris_data)/sum(np.exp(iris_data))
softmax.sum()
softmax

array([0.00578057, 0.00706041, 0.00638852, 0.01053289, 0.01421792,
       0.0086236 , 0.0086236 , 0.00523048, 0.00638852, 0.01164064,
       0.0086236 , 0.00578057, 0.00578057, 0.01571323, 0.02344138,
       0.01421792, 0.00953055, 0.0128649 , 0.0128649 , 0.0086236 ,
       0.01164064, 0.01053289, 0.00780296, 0.0086236 , 0.00578057,
       0.0086236 , 0.00953055, 0.0086236 , 0.00706041, 0.00638852,
       0.0086236 , 0.0173658 , 0.01919218, 0.00638852, 0.00706041,
       0.00953055, 0.00638852, 0.00578057, 0.0086236 , 0.00953055,
       0.00287055, 0.00706041, 0.00953055, 0.0128649 , 0.00578057,
       0.0128649 , 0.00706041, 0.01164064, 0.00780296, 0.00706041,
       0.00706041, 0.00638852, 0.00287055, 0.00473273, 0.00473273,
       0.00780296, 0.00317245, 0.00523048, 0.00428235, 0.00212655,
       0.00578057, 0.00259738, 0.00523048, 0.00523048, 0.00638852,
       0.00578057, 0.00428235, 0.00259738, 0.00350609, 0.00706041,
       0.00473273, 0.00350609, 0.00473273, 0.00523048, 0.00578

In [ ]:
np.percentile(iris_data , q = [5,95])

array([2.34, 3.8 ])

In [ ]:
import random as rand

In [ ]:
iris_data = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1,2,3,4], skip_header=1)

for i in np.random.randint( 0 , len(iris_data) , 20):
  iris_data[i] = np.nan

iris_data



array([[3. , 1.4, 0.2, nan],
       [3.2, 1.3, 0.2, nan],
       [3.1, 1.5, 0.2, nan],
       [3.6, 1.4, 0.2, nan],
       [3.9, 1.7, 0.4, nan],
       [3.4, 1.4, 0.3, nan],
       [3.4, 1.5, 0.2, nan],
       [2.9, 1.4, 0.2, nan],
       [3.1, 1.5, 0.1, nan],
       [3.7, 1.5, 0.2, nan],
       [3.4, 1.6, 0.2, nan],
       [3. , 1.4, 0.1, nan],
       [3. , 1.1, 0.1, nan],
       [4. , 1.2, 0.2, nan],
       [4.4, 1.5, 0.4, nan],
       [3.9, 1.3, 0.4, nan],
       [3.5, 1.4, 0.3, nan],
       [3.8, 1.7, 0.3, nan],
       [nan, nan, nan, nan],
       [3.4, 1.7, 0.2, nan],
       [3.7, 1.5, 0.4, nan],
       [3.6, 1. , 0.2, nan],
       [3.3, 1.7, 0.5, nan],
       [3.4, 1.9, 0.2, nan],
       [3. , 1.6, 0.2, nan],
       [3.4, 1.6, 0.4, nan],
       [3.5, 1.5, 0.2, nan],
       [nan, nan, nan, nan],
       [3.2, 1.6, 0.2, nan],
       [3.1, 1.6, 0.2, nan],
       [3.4, 1.5, 0.4, nan],
       [4.1, 1.5, 0.1, nan],
       [4.2, 1.4, 0.2, nan],
       [3.1, 1.5, 0.1, nan],
       [3.2, 1

In [ ]:
iris_data[np.random.randint(len(iris_data) , size = 20) , np.random.randint(4 , size = 20)] = np.nan
print("Number of missing values in Iris data:",np.isnan(iris_data).sum())
print("Numbers of missing values in first:", np.isnan(iris_data[:,0]).sum())
print("Postion of missing values:", np.where(np.isnan(iris_data[:,0])))

Number of missing values in Iris data: 221
Numbers of missing values in first: 23
Postion of missing values: (array([  1,   4,   9,  10,  12,  20,  21,  24,  25,  27,  56,  58,  86,
        90,  91,  94,  99, 104, 106, 107, 124, 132, 138]),)
